import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowRight, Check, ChevronRight, Home } from 'lucide-react'
import { loanSlugs, getLoanProgram, programSteps, programTestimonial } from '@/app/data/loanPrograms'

export function generateStaticParams() { return loanSlugs }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const program = getLoanProgram(slug); return program ? { title: `${program.title} | Northstar Studio`, description: program.description } : {} }

export default async function LoanProgramPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const program = getLoanProgram(slug)
  if (!program) notFound()
  const steps = programSteps(program)
  const testimonial = programTestimonial(program)
  return <main className="pt-36">
    <section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8 lg:pb-32"><Link href="/loan-programs" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"><ChevronRight className="size-4 rotate-180" /> All loan programs</Link><div className="mt-16 grid gap-12 lg:grid-cols-[1fr_320px] lg:items-end"><div><p className="font-mono text-xs uppercase tracking-[.25em] text-primary">{program.accent}</p><h1 className="mt-6 max-w-4xl text-5xl font-semibold tracking-[-.05em] sm:text-7xl">{program.title}<span className="text-primary">.</span></h1><p className="mt-8 max-w-2xl text-xl leading-8 text-muted-foreground">{program.description}</p><div className="mt-10 flex flex-wrap gap-4"><Link href="/contact" className="inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 font-semibold text-primary-foreground transition hover:brightness-110">Talk with an advisor <ArrowRight className="size-4" /></Link></div></div><div className="rounded-2xl border border-primary/30 bg-primary/10 p-7"><Home className="size-7 text-primary" /><strong className="mt-8 block text-lg">Thoughtful guidance.</strong><p className="mt-2 text-sm leading-6 text-muted-foreground">We&apos;ll explain the details before you make a decision.</p></div></div></section>
    <section className="border-y border-border bg-card"><div className="mx-auto grid max-w-7xl gap-16 px-5 py-24 lg:grid-cols-[1fr_340px] lg:px-8 lg:py-32"><article><p className="font-mono text-xs uppercase tracking-[.25em] text-primary">A closer look</p><h2 className="mt-5 text-4xl font-semibold tracking-tight">{program.title}, made clear.</h2><p className="mt-7 max-w-2xl text-lg leading-8 text-muted-foreground">{program.overview}</p><div className="mt-10 grid gap-4 sm:grid-cols-2">{program.benefits.map(benefit => <div key={benefit} className="flex gap-3 rounded-xl border border-border p-4 text-sm leading-6"><Check className="mt-1 size-4 shrink-0 text-primary" />{benefit}</div>)}</div></article><aside className="rounded-2xl border border-border bg-background p-7"><p className="font-mono text-xs uppercase tracking-[.25em] text-primary">This may fit you if</p><h3 className="mt-5 text-2xl font-semibold">Built around real life.</h3><ul className="mt-7 flex flex-col gap-4 text-sm text-muted-foreground">{program.idealFor.map(item => <li key={item} className="flex gap-3"><Check className="size-4 shrink-0 text-primary" />{item}</li>)}</ul></aside></div></section>
    <section className="mx-auto max-w-7xl px-5 py-24 lg:px-8 lg:py-32"><p className="font-mono text-xs uppercase tracking-[.25em] text-primary">A simpler process</p><h2 className="mt-5 text-4xl font-semibold tracking-tight">From question to keys.</h2><div className="mt-14 grid gap-8 md:grid-cols-3">{steps.map(step => <div key={step.step} className="border-t border-border pt-6"><span className="font-mono text-sm text-primary">0{step.step}</span><h3 className="mt-8 text-xl font-semibold">{step.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{step.description}</p></div>)}</div></section>
    <section className="border-y border-border bg-primary px-5 py-16 text-primary-foreground lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-lg font-medium">“{testimonial.text}”</p><span className="mt-3 block text-sm opacity-70">{testimonial.name}</span></div><Link href="/contact" className="inline-flex items-center gap-2 self-start rounded-full bg-primary-foreground px-5 py-3 font-semibold text-primary transition hover:opacity-90">Start a conversation <ArrowRight className="size-4" /></Link></div></section>
  </main>
}
